### ISSUE TITLE
SVG Payment Icons Distort Order Confirmation EMail in Outlook Office 2019

### ISSUE THREAD

**Issue by nickweisser** [pfpayments/magento-1#1]
Looks like Outlook Office 2019 does not support SVG images. The order confirmation email gets badly distorted. In Thunderbird on macOS and Google webmail it works fine, though:

![Bestellbestaetigungs-Mail_in_Outlook_Office_2019_stark_verzerrt_-_JIRA](https://user-images.githubusercontent.com/58966/177781982-0021a395-a646-497e-a49f-409b3dba8f4a.jpg)
![mail_jpeg](https://user-images.githubusercontent.com/58966/177781987-ee3af803-f182-45c2-b076-c879f7550075.jpg)
.

**Comment by theodorspringwallee** [comment]
Dear [nickw108](https://github.com/nickw108), can you provide us maybe such a mail file, that we can analyze it?
